version: '3'

services:

  postgres:
    image: postgres
    deploy:
      mode: global
    restart: always
    environment:
      POSTGRES_DB: fridge
      POSTGRES_PASSWORD: password
    volumes:
      - "T:/studying/3kurs/5sem/RBD/project/docker-db-volume:/var/lib/postgresql/data"

  backend:
    build: .
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/fridge
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 8080:8080

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080